image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/loopback3-server-master.git HEAD:master --force
